[package]
name = "libvalhalla"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Rust bindings for Valhalla routing engine"
readme = "README.md"
repository = "https://github.com/kinkard/valhalla-debug"
license = "MIT OR Apache-2.0"

[dependencies]
cxx = "1.0"

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"
miniserde = "0.1"     # For compile_commands.json parsing
pkg-config = "0.3"
