name: Sanity Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # For some reason GCC fails to compile valhalla so we use clang instead that we
      # install together with all Valhalla dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            clang \
            build-essential \
            cmake \
            libboost-dev \
            liblz4-dev \
            libprotobuf-dev \
            protobuf-compiler \
            zlib1g-dev

      - name: Set environment variables
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy -- -Dwarnings

      - name: Run tests
        run: cargo test
